name: Races
version: 1.0.0-SNAPSHOT
main: net.nighthawkempires.races.RacesPlugin
description: Nighthawk Empires' Races Plugin.
author: NoneVale_
api-version: 1.17
depend: [Core]
softdepend: [Regions]
commands:
  bind:
    usage: </command>
    description: Bind command for Nighthawk Empires' Races Plugin.
  races:
    aliases: [race]
    usage: </command>
    description: Races command for Nighthawk Empires' Races Plugin.